[phases.setup]
nixPkgs = [
  '...',
  'git',
  # 'cron',
  # 'curl'
]

[phases.build]
cmds = [
  'git submodule update --init',
  'cd ./.vue && npm i && npm run build && rm -rf node_modules && cd ..',
  'mv ./.vue/dist/* ./'
]

# [phases.cron]
# cmds = [
#   'chmod +x /app/.cloudflare/ip-whitelist-sync.sh',
#   'chmod +x /app/.cloudflare/ip-whitelist-sync-init.sh && /app/.cloudflare/ip-whitelist-sync-init.sh',
#   'echo "30 2 * * * /app/.cloudflare/ip-whitelist-sync.sh >/dev/null 2>&1" >> /app/.cloudflare/cloudflare-job',
#   'crontab /app/.cloudflare/cloudflare-job'
# ]
# dependsOn = ['build']

# [start]
# cmd = 'cron && node /assets/scripts/prestart.mjs /app/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)'
