[phases.setup]
nixPkgs = ['...', 'nodejs', 'git']

[phases.build]
cmds = ['git submodule update --init', 'cd ./.vue && npm i && npm run build && rm -rf node_modules && cd ..', 'mv ./.vue/dist/* ./', 'composer i']
